### ISSUE TITLE
Swarmstr events

### ISSUE THREAD

**Issue by mterenzio** [ptrio42/swarmstr.com#14]
This is great. This is really a protocol support question, not a software issue.

Is there any docs which explain the differences between a swarmstr event (kind or any needed metadata etc) that distinguish them from a regular old nostr text note?

Thanks

**Comment by ptrio42** [comment]
Swarmstr event is like any regular note. The only difference is that if you post from swarmstr, asknostr tag is added to event's tags array when it's a question and asknostr-reply for an answer :) Will work on some docs soon.
