### ISSUE TITLE
back from /recent goes back to the start of the last search

### ISSUE THREAD

**Issue by arneschween** [ptrio42/swarmstr.com#4]
when browsing through swarmstr.com/recent and opening a thread, after that clicking on back at the top swarmstr.com/recent returns to the start of the recent #asknostr posts.

**Comment by ptrio42** [comment]
Fixed the navigation issue on desktop. Doesn't seem to work on mobile (Safari, iOS)

**Comment by ptrio42** [comment]
should be working as expected
